name: idireksyon_frontend
description: "IDireksyon mobile application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0
  geolocator: ^13.0.2
  latlong2: ^0.9.0
  http: ^1.6.0
  url_launcher: ^6.2.5
  lottie: ^3.3.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loading.json.json
    - assets/onboarding pictures/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.woff2
          weight: 400
        - asset: assets/fonts/GoogleSans-Medium.woff2
          weight: 500
        - asset: assets/fonts/GoogleSans-SemiBold.woff2
          weight: 600
        - asset: assets/fonts/GoogleSans-Bold.woff2
          weight: 700
    - family: Bricolage Grotesque
      fonts:
        - asset: assets/fonts/BricolageGrotesque.ttf